export default {
	SEARCH: {
		REQUEST: 'SEARCH_REQUEST',
		SUCCESS: 'SEARCH_SUCCESS',
		FAILURE: 'SEARCH_FAILURE'
	},
	REPO: {
		REQUEST: 'REPO_REQUEST',
		SUCCESS: 'REPO_SUCCESS',
		FAILURE: 'REPO_FAILURE'
	}
}
